### PR TITLE
Add installation check script

### PR DESCRIPTION
**Pull request by codytowstik**
This may be useful as a initial triage tool... would need a note somewhere in readme

### CODE REVIEW

**Comment by diracdeltas** [comment]
nice!! this is awesome. does windows ever install python 3.x as python3 instead of python? i was hesitant to hard-code python commands on mac because it could be either one.

**Comment by diracdeltas** [comment]
> this is awesome. does windows ever install python 3.x as python3 instead of python? i was hesitant to hard-code python commands on mac because it could be either one.

i guess what i'm asking is in the README, how should we suggest people run this? `./check-install.py` or `python/python3 check-install.py`?

**Review by diracdeltas — APPROVED** [review]
lgtm, only question is what the command in the readme should be. (i don't use windows so i'm not sure)

i'm guessing `python check-install.py`?

**Comment by codytowstik** [comment]
I don't really use windows either, just happens to be what my Ableton setup is on right now, so i'm not sure 100%... buttt according to my limited experience and [the docs](https://docs.python.org/3/using/windows.html#getting-started) I believe - and was surprised to find out - it is `py check-install.py` and then the shebang at the top will ensure it is run with python3 if they have 2 and 3 installed.

**Comment by codytowstik** [comment]
Closing because this is the wrong branch... pushing to native branch.

**Pull request closed without merging**
