### PR TITLE
Update README with sanity check tips

### PR DESCRIPTION
**Pull request by codytowstik**

### CODE REVIEW

**Comment by b7s9** [comment]
rather than saying "sanity tip" which is a bit user hostile, I'd instead recommend something along the lines of "to test that ffmpeg is successfully installed, run:"

**Comment by diracdeltas** [comment]
@codytowstik thanks for your help with troubleshooting and docs, it's much needed and appreciated here!

i think @b7s9 has a valid point; it's not clear to me that non-programmer or non-native english speakers know the figurative meaning of "sanity check"

**Comment by codytowstik** [comment]
Good call, I sometimes get lost in the dev mindset.

I'll make some mods.

**Review by diracdeltas — APPROVED** [review]
amazing, thank you for doing this!

**Pull request merged**
